#
# Copyright (C) 2009 Realtek Semiconductor Corp. 
#
# Makefile for SDK Linux Rtdrv Kernel Module
#

include $(SDKDIR)/../Compiler_Flag

SDK_BUILD = $(SDKDIR)/build

EXTRA_CFLAGS += -DCONFIG_SDK_KERNEL_LINUX

include $(SDK_BUILD)/Makefile.linux.kernel.rtdrv

