#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "rsdk-linux-gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DTERMIO -Os -fomit-frame-pointer -Wall"
  #define PLATFORM "rsdk-linux"
  #define DATE "Wed Dec  4 15:09:26 CST 2013"
#endif
