# RTL819X Platform Support
snd-soc-rtl819x-objs := rtl819x-pcm.o
snd-soc-rtl8197d-i2s-objs := rtl8197d-i2s.o

obj-$(CONFIG_SND_RTL819XD_SOC_I2S) += snd-soc-rtl819x.o
obj-$(CONFIG_SND_RTL819XD_SOC_I2S) += snd-soc-rtl8197d-i2s.o


# RTL819X Machine Support
snd-soc-rtl819xD-rt5628-objs := rtl819xD_rt5628.o
snd-soc-rtl819xD-rt5642-objs := rtl819xD_rt5642.o
snd-soc-rtl819xD-rt5633-objs := rtl819xD_rt5633.o
snd-soc-rtl819xD-rt5670-objs := rtl819xD_rt5670.o


obj-$(CONFIG_SND_RTL819XD_SOC_ALC5628) += snd-soc-rtl819xD-rt5628.o
obj-$(CONFIG_SND_RTL819XD_SOC_ALC5642) += snd-soc-rtl819xD-rt5642.o
obj-$(CONFIG_SND_RTL819XD_SOC_ALC5633Q) += snd-soc-rtl819xD-rt5633.o
obj-$(CONFIG_SND_RTL819XD_SOC_ALC5670) += snd-soc-rtl819xD-rt5670.o


