cmd_rtk_voip/voip_drivers/proslic_api/src/si_voice_version.o := msdk-linux-gcc -Wp,-MD,rtk_voip/voip_drivers/proslic_api/src/.si_voice_version.o.d  -nostdinc -isystem /home/steve1097/branch-rtl819x-sdk-v3.4.7.3/toolchain/msdk-4.4.7-mips-EB-3.10-0.9.33-m32t-131227b/bin/../lib/gcc/mips-linux-uclibc/4.4.7/include -I/home/steve1097/branch-rtl819x-sdk-v3.4.7.3/linux-3.10/arch/mips/include -Iarch/mips/include/generated  -Iinclude -I/home/steve1097/branch-rtl819x-sdk-v3.4.7.3/linux-3.10/arch/mips/include/uapi -Iarch/mips/include/generated/uapi -I/home/steve1097/branch-rtl819x-sdk-v3.4.7.3/linux-3.10/include/uapi -Iinclude/generated/uapi -include /home/steve1097/branch-rtl819x-sdk-v3.4.7.3/linux-3.10/include/linux/kconfig.h -D__KERNEL__ -DVMLINUX_LOAD_ADDRESS=0x80000000 -DDATAOFFSET=0 -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -mno-check-zero-division -mabi=32 -G 0 -mno-abicalls -fno-pic -pipe -msoft-float -ffreestanding -EB -UMIPSEB -U_MIPSEB -U__MIPSEB -U__MIPSEB__ -UMIPSEL -U_MIPSEL -U__MIPSEL -U__MIPSEL__ -DMIPSEB -D_MIPSEB -D__MIPSEB -D__MIPSEB__ -U_MIPS_ISA -D_MIPS_ISA=_MIPS_ISA_MIPS32 -Wa,-mips32r2 -Wa,--trap -Iinclude/asm-mips -Iarch/mips/bsp/ -I/home/steve1097/branch-rtl819x-sdk-v3.4.7.3/linux-3.10/arch/mips/include/asm/mach-generic -Wframe-larger-than=1024 -fno-stack-protector -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Irtk_voip/include -Irtk_voip/voip_drivers -Irtk_voip/voip_drivers/proslic_api/inc -Irtk_voip/voip_drivers/proslic_api/config_inc -Irtk_voip/voip_drivers/proslic_api/config_src -DREALTEK_PATCH_FOR_SILAB -DSI3217X   -ffunction-sections -fdata-sections  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(si_voice_version)"  -D"KBUILD_MODNAME=KBUILD_STR(si_voice_version)" -c -o rtk_voip/voip_drivers/proslic_api/src/si_voice_version.o rtk_voip/voip_drivers/proslic_api/src/si_voice_version.c

source_rtk_voip/voip_drivers/proslic_api/src/si_voice_version.o := rtk_voip/voip_drivers/proslic_api/src/si_voice_version.c

deps_rtk_voip/voip_drivers/proslic_api/src/si_voice_version.o := \

rtk_voip/voip_drivers/proslic_api/src/si_voice_version.o: $(deps_rtk_voip/voip_drivers/proslic_api/src/si_voice_version.o)

$(deps_rtk_voip/voip_drivers/proslic_api/src/si_voice_version.o):
